default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: kitsumanga
  username: whdzera@gmail.com
  password: pVuyYPQ2vwz7
  host: ep-small-moon-a5nmpbpe-pooler.us-east-2.aws.neon.tech
  port: 5432
  pool: 5
  sslmode: require
  